services:
  - type: static
    name: mygrab-admin
    rootDir: admin-web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://ayvqtjqdorjoczosprjb.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_a0c-O0P_YOPqMmRZ3vVqhw_HKwNIk-3
      - key: VITE_API_BASE_URL
        value: https://mygrab.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: mygrab-api
    runtime: node
    region: singapore
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        value: https://ayvqtjqdorjoczosprjb.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
